### ISSUE TITLE
Dynamic breaks url

### ISSUE THREAD

**Issue by Nebelung-Dev** [MercuryWorkshop/adrift#4]
Also just not working lol. See screenshot

![image](https://github.com/MercuryWorkshop/adrift/assets/81875430/e14519cb-918d-4d8d-bdff-9b30bd77efcc)

**Comment by CoolElectronics** [comment]
it seems to me like the service worker isn't getting registered. try reloading or clearing data?

**Comment by Nebelung-Dev** [comment]
A reload fixes this issue. Still weird how the Dynamic url is not decoded before the sw is registered but it works now!
