### ISSUE TITLE
Sandbox escaping on standalone html file

### ISSUE THREAD

**Issue by localuser-isback** [MercuryWorkshop/adrift#6]
When loading up the standalone html file on a chromeOS system then connecting the swarm it loads google just fine but if i search anything or change URLS the sandbox escapes and it redirects me out of the proxy which gives an error "www.google.com refused to connect." since it cant be iframed, unable to check dev console as its disabled on my system.

**Comment by CoolElectronics** [comment]
this is normal, the standalone file has minimal site support compared to the full Ultraviolet assets-static build

if you want, you can open an issue on MercuryWorkshop/corium about it but do not expect a response

**Comment by localuser-isback** [comment]
So its not usable as a static file since it does this with every website?

**Comment by localuser-isback** [comment]
Damn. Are there any other proxies that might work as a standalone html file?

**Comment by CoolElectronics** [comment]
corium, the backend adrift uses in singlefile mode is the current most advanced html file proxy engine

**Comment by localuser-isback** [comment]
> corium, the backend adrift uses in singlefile mode is the current most advanced html file proxy engine
Ive heard that there are static UV builds but im pretty sure UV does not work without https because of service workers correct?

**Comment by CoolElectronics** [comment]
yes

**Comment by localuser-isback** [comment]
what about something like spadium?

**Comment by CoolElectronics** [comment]
corium is a fork of spadium with more advanced site support

**Comment by localuser-isback** [comment]
Ah okay
