### ISSUE TITLE
@mercuryworkshop/adrift@workspace ERR_PNPM_NO_MATCHING_VERSION 

### ISSUE THREAD

**Issue by happylabdab2** [MercuryWorkshop/adrift#9]
@happylabdab2 ➜ /workspaces/adrift/frontend (master) $ pnpm install
Scope: all 11 workspace projects
..                                       |  WARN  deprecated node-pre-gyp@0.17.0
/workspaces/adrift/client:
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @mercuryworkshop/adrift@workspace*

This error happened while installing a direct dependency of /workspaces/adrift/client

The latest release of @mercuryworkshop/adrift is "1.0.4".

If you need the full list of all 5 published versions run "$ pnpm view @mercuryworkshop/adrift versions".
..                                       | Progress: resolved 50, reused 40, downloaded 4, added 0

**Comment by happylabdab2** [comment]
NVM its a duplicate of https://github.com/MercuryWorkshop/adrift/issues/7

**Comment by Scoder12** [comment]
idts I think it's a typo here https://github.com/MercuryWorkshop/adrift/blob/86aa2e5cbbafd9b6b6fd0ccb6b398d7ed47bbca6/client/package.json#L15
